name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-24.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgl1-mesa-dev libegl1-mesa-dev xvfb

      - name: pull submodules
        run: git submodule update --init --recursive

      - name: install frontend dependencies
        run: npm install # changed from yarn to npm to match package.json scripts

      - name: Validate signing configuration
        shell: bash
        run: |
          if [ -z "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" ]; then
            echo "⚠️  WARNING: TAURI_SIGNING_PRIVATE_KEY secret is not set!"
            echo "This will result in unsigned releases that cannot be auto-updated."
            echo "Please add the signing key to repository secrets."
            exit 1
          else
            echo "✅ Signing key is configured"
          fi

      - name: Setup virtual display (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          NO_STRIP: true # Prevents stripping the binaries which can cause issues with some antivirus software.
          # Fix EGL errors on Linux by disabling GPU acceleration
          WEBKIT_DISABLE_DMABUF_RENDERER: 1
          WEBKIT_DISABLE_COMPOSITING_MODE: 1
          DISPLAY: ${{ matrix.platform == 'ubuntu-24.04' && ':99' || '' }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "v__VERSION__"
          releaseBody: |
            ### Download Instructions
            - **Windows**: Download the `.msi` installer for easy installation
            - **macOS**: Download the `.dmg` file for drag-and-drop installation
            - **Linux**: Download the `.AppImage` for portable execution or `.deb` for system installation

            ### Installation Notes
            - Please ensure you have the latest version of your operating system
            - For first-time installations, you may need to allow the application in your security settings

            **Full Changelog**: https://github.com/${{ github.repository }}/commits/release
          releaseDraft: false
          prerelease: false
          includeRelease: true
          includeUpdaterJson: true
          updaterJsonKeepUniversal: false
          updaterJsonPreferNsis: false
          args: ${{ matrix.args }}